### ISSUE TITLE
Mobile Format is difficult to use

### ISSUE THREAD

**Issue by mxmeinhold** [Dr-N0/Cal#17]
The interface is pretty small, has a lot of scrolling, and getting info about an event is hard, since the modal pops up and disappears immediately.
![cal-cal cs house_(iPhone X)](https://user-images.githubusercontent.com/12436574/75086473-8baeb680-5502-11ea-83f2-ebc1f5e29453.png)

**Comment by mxmeinhold** [comment]
It might be worth considering a day or week view for mobile, so that there's less content to put on the screen at once.

**Comment by Dr-N0** [comment]
That's 80% done with as I'm talking

**Comment by Dr-N0** [comment]
Doing a week view

**Comment by Dr-N0** [comment]
PR open that fixes this
