### ISSUE TITLE
Event details are not immediately apparent

### ISSUE THREAD

**Issue by mxmeinhold** [Dr-N0/Cal#18]
I have to click into each event individually to get times. It'd be nice if events either were prepended with the time they started, or if they visually showed when they occurred, so I didn't have to click each individual event to know whats happening in a given night.

**Comment by Dr-N0** [comment]
Getting fixed with the mobile update (code is 95% done as we talk)

**Comment by mxmeinhold** [comment]
Will that also fix it on desktop views?

**Comment by Dr-N0** [comment]
👌

**Comment by Dr-N0** [comment]
PR up that fixes this
